### PR TITLE
[dattri.func.ihvp] Implement ihvp_at_x_ekfac

### PR DESCRIPTION
**Pull request by sx-liu**
### 1. Motivation and Context

This PR is the same as the closed one #79.

To complete the proposal in the issue #76.

### 2. Summary of the change

The implementation is basically the same as originally designed.

Specifically,
- Added `ihvp_at_x_ekfac` and its helper functions to `dattri.func.ihvp`.
- Added wrapper function `manual` and class `MLPCache` to `dattri.func.ihvp`.
- Slightly modified `dattri.func.ihvp._check_input_size` to support the EK-FAC method.

### 3. What tests have been added/updated for the change?
- [x] Unit test: Typically, this should be included if you implemented a new function/fixed a bug.

### CODE REVIEW

**Comment by sx-liu** [comment]
Seems like `test_ihvp_datainf_nn ` is a bit shaky.

**Review by jiaqima — APPROVED** [review]

**Comment by jiaqima** [comment]
> Seems like `test_ihvp_datainf_nn ` is a bit shaky.

Could lower the threshold to 0.8.

**Comment by sx-liu** [comment]
> > Seems like `test_ihvp_datainf_nn ` is a bit shaky.
> 
> Could lower the threshold to 0.8.

Should I do it here or in a separate PR?

**Comment by jiaqima** [comment]
> > > Seems like `test_ihvp_datainf_nn ` is a bit shaky.
> > 
> > 
> > Could lower the threshold to 0.8.
> 
> Should I do it here or in a separate PR?

You could just do it here. This shaky test is going to block other PRs if we merge this PR without lowering the threshold.

**Pull request merged**
