### PR TITLE
Improve docstring in dattri.func and dattri.metrics

### PR DESCRIPTION
**Pull request by jiaqima**
## Description

This PR mainly improves the docstring of files under dattri.func and dattri.metrics.

### 1. Motivation and Context

There are some format inconsistency issues and typos in the docstrings. 

### 2. Summary of the change

- Improved docstring by making the format more consistent and fixing some typos
- For `dattri/func/utils.py`, changed all `torch.Tensor` to `Tensor` since it is imported
- Fixed a typo in `dattri/task.py`: `_genearte_param_layer_map` -> `_generate_param_layer_map`
- Changed `calculate_loo_groundtruth` in `dattri/metrics/ground_truth.py` to `calculate_loo_ground_truth`. Also changed all the references to this function.

### 3. What tests have been added/updated for the change?
-  N/A: No test will be added. Mainly changed docstring and `torch.Tensor` to `Tensor`. The only code change is a membership function name in `task.py` and a util function in `ground_truth.py`, which should be fine.

### CODE REVIEW

**Comment by jiaqima** [comment]
@TheaperDeng what will be affected if we change `calculate_loo_groundtruth` in `ground_truth.py` to `calculate_loo_ground_truth`? Its name format is now inconsistent with `calculate_lds_ground_truth`.

**Comment by TheaperDeng** [comment]
> @TheaperDeng what will be affected if we change `calculate_loo_groundtruth` in `ground_truth.py` to `calculate_loo_ground_truth`? Its name format is now inconsistent with `calculate_lds_ground_truth`.

I think the only thing is to search this function in all the calls in code and documentation and change it throughout the repo. There might be several place be affected, mostly in `benchmark` and `model_utils` folders

**Comment by jiaqima** [comment]
> > @TheaperDeng what will be affected if we change `calculate_loo_groundtruth` in `ground_truth.py` to `calculate_loo_ground_truth`? Its name format is now inconsistent with `calculate_lds_ground_truth`.
> 
> I think the only thing is to search this function in all the calls in code and documentation and change it throughout the repo. There might be several place be affected, mostly in `benchmark` and `model_utils` folders

The only two files are `dattri/metrics/ground_truth.py` and `docs/source/api/benchmark.rst`.

**Comment by jiaqima** [comment]
Merging this PR to avoid it getting conflicts with other PRs, as this involves multiple files.

**Pull request merged**
